name: 'Tada'
description: 'Todo management system'
inputs:
  token:
    description: 'Access token for manage issue'
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
