#!/bin/sh

set -e
set -v

pycodestyle --ignore=W191,E117 .

pylint --disable=W0312,W0621,C0330 *.py

# @todo #21 Enable WPS110 flake8 warning
# @todo #21 Enable WPS210 flake8 warning
# @todo #21 Enable WPS211 flake8 warning
# @todo #21 Enable WPS226 flake8 warning
# @todo #21 Enable WPS230 flake8 warning
# @todo #21 Enable WPS335 flake8 warning
# @todo #21 Enable WPS426 flake8 warning
flake8 --ignore=W191,E117,C812,S001,T001,D401,WPS210,WPS110,WPS335,WPS426,WPS221,C815,WPS306,S303,A003,WPS602,I002,WPS226,WPS230

./test.py
