on:
  push:
    branches-ignore:
      - master

# @todo Check python syntax
# @todo Check TODO syntax
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check style
    steps:
      - name: Checkout
        uses: actions/checkout@v1
