on:
  push:
    branches-ignore:
      - master

# @todo #15 Check python syntax with flakes8
# @todo Check TODO syntax
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check style
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pycodestyle pylint pygithub
      - run: pycodestyle --ignore=W191,E117 .
      - run: pylint --disable=W0312,W0621,C0330 *.py
      - run: ./test.py
