on:
  push:
    branches-ignore:
      - master

# @todo #9 Check python syntax with pylint
# @todo Check TODO syntax
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check style
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: |
        pip install pycodestyle
        pycodestyle --ignore=W191,E117 .
